/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import java.io.File;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import mechdata.Mech;
import mechdata.MechChooser;
import mechdata.MechContainer;
import mechdata.Variant;
import sounds.SoundMaster;

/**
 *
 * @author StevenKiley
 */
public class DoublePanel extends javax.swing.JPanel {
    MechContainer mechs;
    /**
     * Creates new form screwUp
     */
    public DoublePanel(MechContainer m) {
        mechs = m;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mechChoices = new javax.swing.ButtonGroup();
        resultPanel = new javax.swing.JPanel();
        upperResultPic = new javax.swing.JLabel();
        lowerResultPic = new javax.swing.JLabel();
        centerLogo = new javax.swing.JLabel();
        resultText = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        upperDivider = new javax.swing.JSeparator();
        banner = new javax.swing.JLabel();
        allMechs = new javax.swing.JRadioButton();
        isMechs = new javax.swing.JRadioButton();
        clanMechs = new javax.swing.JRadioButton();
        lowerDivider = new javax.swing.JSeparator();
        bannerPic = new javax.swing.JLabel();
        chooseFrom = new javax.swing.JLabel();
        weightClasses = new javax.swing.JLabel();
        lowerBanner = new javax.swing.JLabel();
        actionButton = new javax.swing.JButton();
        lightMechs = new javax.swing.JCheckBox();
        mediumMechs = new javax.swing.JCheckBox();
        heavyMechs = new javax.swing.JCheckBox();
        assaultMechs = new javax.swing.JCheckBox();
        rightArrow = new javax.swing.JLabel();
        leftArrow = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        resultPanel.setBackground(new java.awt.Color(204, 255, 102));

        upperResultPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Images/Mechs/Battle3.png"))); // NOI18N

        lowerResultPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Images/Mechs/Battle2.jpg"))); // NOI18N

        centerLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Images/Mechs/mwo-banner.jpg"))); // NOI18N

        resultText.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        resultText.setForeground(new java.awt.Color(102, 0, 0));
        resultText.setText("Made by Steven Kiley");

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(centerLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(upperResultPic, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lowerResultPic))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultText)
                .addGap(92, 92, 92))
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(upperResultPic)
                .addGap(0, 0, 0)
                .addComponent(centerLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lowerResultPic))
        );

        menuPanel.setBackground(new java.awt.Color(204, 255, 102));

        upperDivider.setBackground(new java.awt.Color(51, 51, 0));

        banner.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        banner.setForeground(new java.awt.Color(102, 0, 0));
        banner.setText("Mech Chooser");

        allMechs.setBackground(new java.awt.Color(204, 255, 102));
        mechChoices.add(allMechs);
        allMechs.setFont(new java.awt.Font("Stencil", 0, 10)); // NOI18N
        allMechs.setSelected(true);
        allMechs.setText("All Mechs");
        allMechs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allMechsActionPerformed(evt);
            }
        });

        isMechs.setBackground(new java.awt.Color(204, 255, 102));
        mechChoices.add(isMechs);
        isMechs.setFont(new java.awt.Font("Stencil", 0, 10)); // NOI18N
        isMechs.setText("Inner sphere mechs");
        isMechs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isMechsActionPerformed(evt);
            }
        });

        clanMechs.setBackground(new java.awt.Color(204, 255, 102));
        mechChoices.add(clanMechs);
        clanMechs.setFont(new java.awt.Font("Stencil", 0, 10)); // NOI18N
        clanMechs.setText("Clan Mechs");

        lowerDivider.setBackground(new java.awt.Color(51, 51, 0));

        bannerPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Images/Menu/Banner Pic.jpe"))); // NOI18N

        chooseFrom.setFont(new java.awt.Font("Stencil", 1, 12)); // NOI18N
        chooseFrom.setForeground(new java.awt.Color(102, 0, 0));
        chooseFrom.setText("omni and battle mech choices");

        weightClasses.setFont(new java.awt.Font("Stencil", 1, 12)); // NOI18N
        weightClasses.setForeground(new java.awt.Color(102, 0, 0));
        weightClasses.setText("weight class choices");

        lowerBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Images/Menu/banner 2.jpg"))); // NOI18N

        actionButton.setBackground(new java.awt.Color(102, 102, 102));
        actionButton.setFont(new java.awt.Font("Stencil", 1, 12)); // NOI18N
        actionButton.setText("Choose my mech!");
        actionButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 51, 51)));
        actionButton.setContentAreaFilled(false);
        actionButton.setOpaque(true);
        actionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actionButtonMouseClicked(evt);
            }
        });
        actionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionButtonActionPerformed(evt);
            }
        });

        lightMechs.setBackground(new java.awt.Color(204, 255, 102));
        lightMechs.setFont(new java.awt.Font("Stencil", 0, 10)); // NOI18N
        lightMechs.setSelected(true);
        lightMechs.setText("Light Mechs");

        mediumMechs.setBackground(new java.awt.Color(204, 255, 102));
        mediumMechs.setFont(new java.awt.Font("Stencil", 0, 10)); // NOI18N
        mediumMechs.setSelected(true);
        mediumMechs.setText("medium mechs");

        heavyMechs.setBackground(new java.awt.Color(204, 255, 102));
        heavyMechs.setFont(new java.awt.Font("Stencil", 0, 10)); // NOI18N
        heavyMechs.setSelected(true);
        heavyMechs.setText("heavy mechs");

        assaultMechs.setBackground(new java.awt.Color(204, 255, 102));
        assaultMechs.setFont(new java.awt.Font("Stencil", 0, 10)); // NOI18N
        assaultMechs.setSelected(true);
        assaultMechs.setText("assault mechs");

        rightArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Images/Menu/arrow.png"))); // NOI18N

        leftArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Images/Menu/arrow2.png"))); // NOI18N

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(bannerPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addGap(169, 170, Short.MAX_VALUE)
                .addComponent(banner)
                .addGap(182, 182, 182))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lowerBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(allMechs)
                        .addGap(42, 42, 42)
                        .addComponent(isMechs)
                        .addGap(58, 58, 58)
                        .addComponent(clanMechs))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lightMechs)
                            .addComponent(mediumMechs))
                        .addGap(48, 48, 48)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heavyMechs)
                            .addComponent(assaultMechs)))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(weightClasses))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(chooseFrom))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(upperDivider, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lowerDivider, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(leftArrow)
                .addGap(64, 64, 64)
                .addComponent(actionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rightArrow)
                .addGap(32, 32, 32))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(banner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(upperDivider, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseFrom)
                .addGap(21, 21, 21)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clanMechs)
                    .addComponent(isMechs)
                    .addComponent(allMechs))
                .addGap(32, 32, 32)
                .addComponent(bannerPic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lowerDivider, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weightClasses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heavyMechs)
                    .addComponent(lightMechs))
                .addGap(7, 7, 7)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assaultMechs)
                    .addComponent(mediumMechs))
                .addGap(24, 24, 24)
                .addComponent(lowerBanner)
                .addGap(18, 18, 18)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightArrow)
                    .addComponent(leftArrow))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(resultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void allMechsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allMechsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allMechsActionPerformed

    private void isMechsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isMechsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isMechsActionPerformed

    private void actionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionButtonActionPerformed

        
    }//GEN-LAST:event_actionButtonActionPerformed

    private void actionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionButtonMouseClicked
        SoundMaster sm = new SoundMaster();
        SoundMaster.playButton();
        boolean all = this.allMechs.isSelected();
        boolean clan = this.clanMechs.isSelected();
        boolean is = this.isMechs.isSelected();
        boolean light = this.lightMechs.isSelected();
        boolean medium = this.mediumMechs.isSelected();
        boolean heavy = this.heavyMechs.isSelected();
        boolean assault = this.assaultMechs.isSelected();
        int[] faction = factionHelper(all, clan, is);
        int[] wc = weightClassHelper(light, medium, heavy, assault);
        Integer choice = MechChooser.chooseRandomMech(mechs.getRandomChoiceData(faction, wc));
        Mech m = this.mechs.getMech(choice);
        Variant var = varChooser(m); 
        String upperBannerString = picFinder("Upper", m);
        String lowerBannerString = picFinder("Lower", m);
        upperResultPic.setIcon(new javax.swing.ImageIcon(getClass().getResource(upperBannerString)));
        lowerResultPic.setIcon(new javax.swing.ImageIcon(getClass().getResource(lowerBannerString)));
        resultText.setText("MECH CHOICE is :" + m.getChassisName() + " --- " + var.getVarName());
    }//GEN-LAST:event_actionButtonMouseClicked

private int[] factionHelper(boolean a, boolean c, boolean is){
    if(a == true){return new int[]{1,2};}
    if(c == true){return new int[]{2};}
    else{return new int[]{1};}
}   

private int[] weightClassHelper(boolean l, boolean m, boolean h, boolean a){
    ArrayList<Integer> ints = new ArrayList<Integer>();
    if(l == true){ints.add(1);}
    if(m == true){ints.add(2);}
    if(h == true){ints.add(3);}
    if(a == true){ints.add(4);}
    int[] intArray = ints.stream().mapToInt(i->i).toArray();
    return intArray;
}

private Variant varChooser(Mech m){
    ArrayList<Variant> vars = m.getVariants();
    Random rand = new Random();
    int i = rand.nextInt(vars.size());
    return vars.get(i);
}

private String picFinder(String banner, Mech m){
    String def = "/userinterface/Images/Mechs/MadDog.jpg";
    String png = "./src/userinterface/Images/Mechs/"+m.getChassisName()+"/" + m.getChassisName()+banner + ".png";
    String jpg = "./src/userinterface/Images/Mechs/"+m.getChassisName()+"/" + m.getChassisName()+banner + ".jpg";
    String jpeg = "./src/userinterface/Images/Mechs/"+m.getChassisName()+"/" + m.getChassisName()+banner + ".jpeg";
    File f1 = new File(png);
    File f2 = new File(jpg);
    File f3 = new File(jpeg);
    if(f1.exists()){def = png.replace("./src", "");}
    if(f2.exists()){def = jpg.replace("./src", "");}
    if(f3.exists()){def = jpeg.replace("./src", "");}
    return def;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionButton;
    private javax.swing.JRadioButton allMechs;
    private javax.swing.JCheckBox assaultMechs;
    private javax.swing.JLabel banner;
    private javax.swing.JLabel bannerPic;
    private javax.swing.JLabel centerLogo;
    private javax.swing.JLabel chooseFrom;
    private javax.swing.JRadioButton clanMechs;
    private javax.swing.JCheckBox heavyMechs;
    private javax.swing.JRadioButton isMechs;
    private javax.swing.JLabel leftArrow;
    private javax.swing.JCheckBox lightMechs;
    private javax.swing.JLabel lowerBanner;
    private javax.swing.JSeparator lowerDivider;
    private javax.swing.JLabel lowerResultPic;
    private javax.swing.ButtonGroup mechChoices;
    private javax.swing.JCheckBox mediumMechs;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JLabel resultText;
    private javax.swing.JLabel rightArrow;
    private javax.swing.JSeparator upperDivider;
    javax.swing.JLabel upperResultPic;
    private javax.swing.JLabel weightClasses;
    // End of variables declaration//GEN-END:variables

    private void drawNewResult() {
        throw new UnsupportedOperationException("Not supported yet."); 
        
    }
}
